version: '3.8'

services:
  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # Porta diferente para não conflitar
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 5
